#! /usr/bin/bash

find PythonicGcodeMachine -name "flycheck*.py" -exec rm {} \;
find PythonicGcodeMachine -name "parsetab.py" -exec rm {} \;
find PythonicGcodeMachine -name "lextab.py" -exec rm {} \;

# rm -r doc/build
# rm -r doc/sphinx/source/api

api=doc/sphinx/source/api
rm -rf ${api}

python3 PythonicGcodeMachine/Gcode/Rs274/data/make-rst.py

echo
echo Generate RST API files
pyterate-rst-api PythonicGcodeMachine

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
